pipeline {

agent {
    kubernetes {
      yaml """
kind: Pod
spec:
  containers:
      - name: maven
        image: maven:3.3.9-jdk-8-alpine
        command:
        - cat
        tty: true
        env:          
"""
    }
  }
    
    stages {
        stage('Build') {
          steps {
            echo "${previewEnvHostname}"
            echo "${emailRecipient}"
            sh "./mvnw clean install"
          }
        }
    }
}
